meta_product_name: "Plantastic"
meta_title: "Plantastic - Making plant care simplistic"
meta_description: "Making plant care simplistic"
meta_image: "favicon.png" # should exist in `app/assets/images/`
meta_url: "https://www.plantasticapp.live"
